export const list = [
  {
    title: '成交金额',
    titleTips: '所有渠道销售成交金额总和',
    amount: 0,
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeAmount: 0,
    toMonthPayRatio: 0,
    freeContemporaneousPeriodAmount: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payAmount: 0,
    payContemporaneousPeriodAmount: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0
  },
  {
    title: '成交金额',
    titleTips: '成交金额为订单实付金额汇总。',
    amount: 0,
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeAmount: 0,
    freeContemporaneousPeriodAmount: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payAmount: 0,
    payContemporaneousPeriodAmount: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0
  },
  {
    title: '退款金额',
    titleTips: '已成功退款的退款金额总和',
    refundRate: 0,
    amount: 0,
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeAmount: 0,
    freeContemporaneousPeriodAmount: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payAmount: 0,
    payContemporaneousPeriodAmount: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0
  },
  {
    title: '成交订单数',
    titleTips: '成交订单数为已支付的订单总数。',
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeContemporaneousPeriodOrderTotal: 0,
    payContemporaneousPeriodOrderTotal: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0,
    total: 0,
    freeOrderTotal: 0,
    payOrderTotal: 0
  },
  {
    title: '退款订单数',
    titleTips: '退款订单数为已成功退款的订单总数。',
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeContemporaneousPeriodOrderTotal: 0,
    payContemporaneousPeriodOrderTotal: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0,
    total: 0,
    freeOrderTotal: 0,
    payOrderTotal: 0
  },
  {
    title: '直播带货',
    titleTips: '由直播带货产生的业绩总和',
    amount: 0,
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeAmount: 0,
    freeContemporaneousPeriodAmount: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payAmount: 0,
    payContemporaneousPeriodAmount: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0
  },
  {
    title: '内容带货',
    titleTips: '由达人账号内容带货产生的业绩总和',
    amount: 0,
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeAmount: 0,
    freeContemporaneousPeriodAmount: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payAmount: 0,
    payContemporaneousPeriodAmount: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0
  },
  {
    title: '自然成交',
    titleTips: '非直播带货、内容带货产生的订单实付金额汇总。',
    amount: 0,
    currentMonthAmount: 0,
    monthPriceProportion: 0,
    toDayAmount: 0,
    contemporaneousPeriodAmount: 0,
    contemporaneousPeriodRatio: 0,
    freeAmount: 0,
    freeContemporaneousPeriodAmount: 0,
    freeContemporaneousPeriodRatio: 0,
    freeRatio: 0,
    payAmount: 0,
    payContemporaneousPeriodAmount: 0,
    payContemporaneousPeriodRatio: 0,
    payRatio: 0
  }
]
