export const account = {
  'credits': 0,
  'fans': 0,
  'field': '',
  'indexs': 0,
  'jobject': '',
  'level': 0,
  'privilleges': 0,
  'reads': 0,
  'scores': 0,
  'totalContents': 0,
  'totalRecommends': 0,
  'totalRevenue': 0,
  'totalViews': 0,
  'updateTime': ''
}
export const accountContent = {
  'addFans': 0,
  'addReading': 0,
  'averagePlayTime': 0,
  'collections': 0,
  'comment': 0,
  'conmentGreats': 0,
  'contents': 0,
  'createTime': '',
  'dateTime': '',
  'endPlay': 0,
  'fans': 0,
  'fansPlay': 0,
  'fansReading': 0,
  'fansRecommend': 0,
  'forwardConmentGreats': 0,
  'forwards': 0,
  'greats': 0,
  'play': 0,
  'readRate': 0,
  'reading': 0,
  'recommend': 0,
  'shared': 0
}
export const contents1 = {
  'collection': 0,
  'comment': 0,
  'createTime': '',
  'failReason': '',
  'frontCoverImage': '',
  'greats': 0,
  'number': 0,
  'openUrl': '',
  'orgId': 0,
  'platDocId': '',
  'publishId': '',
  'reading': 0,
  'releaseTime': '',
  'shared': 0,
  'status': '',
  'syncContentType': '',
  'title': '',
  'updateTime': ''
}
